version: 7.6.0.0.{build}
image: Visual Studio 2015

branches:
  only:
    - latestw_all
    - hotfix

init:
  - ps: |
      [Environment]::OSVersion | fl *

build_script:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1
      Invoke-AppVeyorBuild

after_build:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1
      Install-OpenSSH

before_test:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1
      Set-OpenSSHTestEnvironment -Confirm:$false

test_script:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1
      Invoke-OpenSSHTests

after_test:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1
      Publish-OpenSSHTestResults
      
on_finish:
  - ps: |      
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1
      Publish-Artifact