version: 0.0.4.0.{build}
image: Visual Studio 2015

branches:
  only:
    - TroubleShootCISysem
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppVeyor.psm1
      Invoke-AppVeyorBuild

before_test:
  - ps: Install-OpenSSH
  - ps: Write-Verbose "Restart computer ..."
  - ps: Restart-Computer -ComputerName localhost -Force
  - ps: Start-Sleep -s 5 # Needs to be proceeded with -ps: as it's interpreted by AppVeyor
  - ps: Write-Verbose "Restart computer completed"

test_script:
  - ps: |
      & "$env:ProgramFiles\PowerShell\6.0.0.12\powershell.exe"
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppVeyor.psm1
      Run-OpenSSHTests -uploadResults
      
on_finish:
  - ps: Publish-Artifact