version: 0.0.8.0.{build}
image: Visual Studio 2015

branches:
  only:
    - latestw_all
    - latestw_all_openssl

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1 -DisableNameChecking
      Invoke-AppVeyorBuild

after_build:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1 -DisableNameChecking
      Install-OpenSSH
  - ps: Write-Verbose "Restart computer ..."
  - ps: Restart-Computer -Force
  - ps: Start-Sleep -s 5 # Needs to be proceeded with -ps: as it's interpreted by AppVeyor
  - ps: Write-Verbose "Restart computer completed!"

before_test:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1 -DisableNameChecking
      Install-OpenSSHTestDependencies
      Deploy-OpenSSHTests
      Setup-OpenSSHTestEnvironment -Quiet

test_script:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1 -DisableNameChecking
      Run-OpenSSHTests

after_test:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1 -DisableNameChecking
      Upload-OpenSSHTestResults
      
on_finish:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1 -DisableNameChecking
      Publish-Artifact
