version: 7.9.0.0.{build}
image: Visual Studio 2015

branches:
  only:
    - latestw_all
    - hotfix

build_script:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1
      Invoke-AppVeyorBuild

after_build:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1
      Install-OpenSSH
      Install-Pester

test_script:
  - ps: |
      Import-Module pester -force
      Invoke-Pester "$($env:APPVEYOR_BUILD_FOLDER)\regress\pesterTests\SSH.Tests.ps1"

after_test:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1
      Publish-OpenSSHTestResults
      
on_finish:
  - ps: |      
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1
      Publish-Artifact